version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          filters:
            branches:
              only:
                - circleci
          auth:
            - aws-cli/setup:
              aws_access_key_id: PREPROD_AWS_ACCESS_KEY_ID
              aws_secret_access_key: PREPROD_AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: .
          repo: vams-base
          tag: "$CIRCLE_SHA1"