version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          filters:
            branches:
              only:
                - circleci
          auth:
            - aws-cli/setup:
                aws_access_key_id: PREPROD_AWS_ACCESS_KEY_ID
                # aws_access_key_id: PREPROD_AWS_ACCESS_KEY_ID
                aws_secret_access_key: PREPROD_AWS_SECRET_ACCESS_KEY
                region: PREPROD_AWS_REGION
          dockerfile: Dockerfile
          path: .
          # account_id: "338371209378"
          account_id: "$PREPROD_AWS_ACCOUNT_ID"
          region: "us-west-2"
          # region: "$PREPROD_AWS_REGION"
          repo: vams-base
          push_image: true
          # executors: base
          extra_build_args: '--compress'
          no_output_timeout: 20m
          tag: latest,"$CIRCLE_SHA1"