version: 2.1


orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0


jobs:
  docker-build-and-push:
    executor:
      name: aws-ecr/default
    steps:
      - aws-ecr/build_and_push_image:
            auth:
              - aws-cli/setup:
                  aws_access_key_id: AWS_ACCESS_KEY_ID
                  aws_secret_access_key: AWS_SECRET_ACCESS_KEY
            dockerfile: Dockerfile
            path: .
            account_id: "$AWS_ACCOUNT_ID"
            region: "eu-central-1"
            repo: vams-base
            push_image: true
            extra_build_args: '--compress'
            no_output_timeout: 20m
            tag: "$CIRCLE_SHA1"
  install_vams:
    docker:
      - image: 456905064851.dkr.ecr.eu-central-1.amazonaws.com/vams-base:670da5fed641329e7b1e607dfd5c129d65b0f804
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - run:
          name: "Every Day Tests"
          command: "ls -lah"
      - run:
          name: "Show env variables"
          command: "env"
      - run:
          name: "Current folder"
          command: "pwd"
      - run:
          name: "List /tmp"
          command: "ls -lah /tmp"
      - run:
          name: "Get VAMS"
          command: |
            git clone https://github.com/awslabs/visual-asset-management-system.git .
            ls -lah
            cd ./web && nvm use
  deploy:
    docker:
      - image: 456905064851.dkr.ecr.eu-central-1.amazonaws.com/vams-base:670da5fed641329e7b1e607dfd5c129d65b0f804
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - run:
          name: "Full Test Suite"
          command: "ls -lah"
      - run:
          name: "Deploy to Production Infrastructure"
          command: "cat /etc/*release"

workflows:
  main:
    jobs:
      - docker-build-and-push:
            filters:
              branches:
                only:
                  - circleci
      - install_vams:
          requires:
            - docker-build-and-push
          filters:
            tags:
              only: /^\d{4}\.\d+$/
      - deploy:
          requires:
            - install_vams
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d{4}\.\d+$/
