version: 2.1


orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0


jobs:
  docker-build-and-push:
    executor:
      name: aws-ecr/default
    steps:
      - aws-ecr/build_and_push_image:
            auth:
              - aws-cli/setup:
                  aws_access_key_id: AWS_ACCESS_KEY_ID
                  aws_secret_access_key: AWS_SECRET_ACCESS_KEY
            dockerfile: Dockerfile
            path: .
            account_id: "$AWS_ACCOUNT_ID"
            region: "eu-central-1"
            repo: vams-base
            push_image: true
            extra_build_args: '--compress'
            no_output_timeout: 20m
            tag: "$CIRCLE_SHA1"
  install_vams:
    docker:
      - image: 456905064851.dkr.ecr.eu-central-1.amazonaws.com/vams-base:e60863671f75fda2d0f1cce33d845d3516847ada
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - run:
          name: "Every Day Tests"
          command: "ls -lah"
      - run:
          name: "Check image release"
          command: "cat /etc/*release"
      - run:
          name: "Current folder"
          command: "pwd"
      - run:
          name: "List root"
          command: "ls -lah /"
      - run:
          name: "Get VAMS"
          command: |
            git clone https://github.com/awslabs/visual-asset-management-system.git
            ls -lah
  deploy:
    docker:
      - image: 456905064851.dkr.ecr.eu-central-1.amazonaws.com/vams-base:e60863671f75fda2d0f1cce33d845d3516847ada
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - run:
          name: "Full Test Suite"
          command: "ls -lah"
      - run:
          name: "Deploy to Production Infrastructure"
          command: "cat /etc/*release"

workflows:
  main:
    jobs:
      - docker-build-and-push:
            filters:
              branches:
                only:
                  - circleci
      - build:
          filters:
            tags:
              only: /^\d{4}\.\d+$/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d{4}\.\d+$/

######
# version: 2.1

# orbs:
#   aws-cli: circleci/aws-cli@4.0
#   aws-ecr: circleci/aws-ecr@9.0

# workflows:
#   build_and_push_image:
#     jobs:
#       - aws-ecr/build_and_push_image:
#           filters:
#             branches:
#               only:
#                 - circleci
#           auth:
#             - aws-cli/setup:
#                 # aws_access_key_id: PREPROD_AWS_ACCESS_KEY_ID
#                 aws_access_key_id: AWS_ACCESS_KEY_ID
#                 aws_secret_access_key: AWS_SECRET_ACCESS_KEY
#                 # aws_secret_access_key: PREPROD_AWS_SECRET_ACCESS_KEY
#                 # region: PREPROD_AWS_REGION
#           dockerfile: Dockerfile
#           path: .
#           # account_id: "338371209378"
#           # account_id: "$PREPROD_AWS_ACCOUNT_ID"
#           account_id: "$AWS_ACCOUNT_ID"
#           region: "eu-central-1"
#           # region: "us-west-2"
#           # region: "$PREPROD_AWS_REGION"
#           repo: vams-base
#           push_image: true
#           # executors: base
#           extra_build_args: '--compress'
#           no_output_timeout: 20m
#           tag: "$CIRCLE_SHA1"